version: '3.8'

services:
  gateway-module:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway-module
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - tps-network

networks:
  tps-network:
    driver: bridge
